variable env {}
variable app {}
variable "app_tag" {}
variable minimum_scale {}
variable maximum_scale {}
variable desired_scale {}
variable target_group_arn {}
variable target_subnet_ids {}
variable lc_sec_group {}
variable instance_key_name {}
variable instance_type {}