version: 2.1
jobs:
  tests:
    docker:
      - image: python:3.6-slim-stretch
    steps:
      - checkout
      - run:
          name: Run application tests
          command: |
            pip3 install pipenv
            cd base-test-api/
            pipenv install
            BASE_API_ENV=test pipenv run pytest
  build-docker:
    machine: true
    steps:
      - checkout
      - run: |
          echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run: docker build -t cadugoncalves96/ping-pong:latest .
      - run: docker push cadugoncalves96/ping-pong:latest
  run-terraform:
    docker:
      - image: hashicorp/terraform:light
    steps:
      - checkout
      - run: |
          cd terraform && terraform init && terraform apply -var-file="production.tfvars" -auto-approve 
workflows:
  version: 2.1
  test-build-deploy:
    jobs:
      - tests
      - build-docker:
          requires:
            - tests
      - run-terraform:
          requires:
            - build-docker