variable app {}
variable env {}
variable lb_sec_group {}
variable target_subnet_ids {}
variable vpc_id {}
variable "domain_name" {}
variable "lb_certificate" {}
variable "api_name" {}
variable "zone_id" {}